[project]
name = "image2sqlitedbmap"
version = "0.2.0"
description = "Packing an image into sqlitedb for use with navigation software such as osmand"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "gdal>=3.8,<3.12.4",
    "mbutil>=0.3.0",
    "numpy>=1.26",
    "pillow>=10.0.0",
    "pyproj>=3.6",
]
[tool.setuptools]
py-modules = ["main", "map_parser", "transformer", "tiler", "database", "map_calc_tools"]

[tool.ruff]
line-length = 120
