[project]
name = "image2sqlitedbmap"
version = "0.1.0"
description = "Packing an image into sqlitedb for use with navigation software such as osmand"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.8.0",
    "pillow>=12.0.0",
]
[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]
pythonpath = "."
# python_files = test_*.py *_test.py
# python_functions = test_*
addopts = [
#   "-vv",				        # подробнейший вывод хода теста
  "-v",				            # более подробный вывод хода теста
  "--import-mode=importlib"  	# меньше проблем с импортами
]
